project:
  type: website
  output-dir: build

website:
  title: "DREAM Lab Cloud Services"
  navbar:
    left:
      - text: Coder Workspaces
        menu:
        - text: Overview
          href: coder.qmd
        - text: "---"
        - text: Getting Started
          href: guides/getting-started.qmd
        - text: Transferring Files
          href: guides/file-transfer.qmd
        - text: "---"
        - text: RStudio
          href: guides/rstudio.qmd
        - text: Marimo Notebooks
          href: guides/marimo.qmd
        - text: Using AI Coding Agents
          href: guides/ai-agents.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto